### PR TITLE
Update items_post.md

### PR DESCRIPTION
**Pull request by azamatsmith**
## Reason 

Response code table is not rendering correctly.

## Changes

- Removed line 529 that was causing the table to render incorrectly.

## Notes 
The table now displays correctly: 

image

### CODE REVIEW

**Comment by rivkahstandig3636** [comment]
@azamatsmith The docs currently are rendering the same without this change on our site. What did they look like to you prior to this change?

**Comment by azamatsmith** [comment]
@rivkahstandig3636 In the new marketing site and on GitHub they do not show up correctly. 
Here is what they look like in a GitHub preview: 

image

**Comment by azamatsmith** [comment]
@rivkahstandig3636 It would be great if we could get this merged for the launch of the new site today 😀

**Comment by brianr** [comment]
@azamatsmith Thanks! This will have a conflict; I'll close this PR and make this change in the other branch.

**Pull request closed without merging**
